Update

diff --git a/mdl b/mdl
--- a/mdl
+++ b/mdl
@@ -1,5 +1,28 @@
 #!/bin/sh
 
+# Ensure that the user has provided a URL
+if [ "$#" -ne 1 ]
+then
+    echo "Usage: mdl <url>"
+    exit
+fi
+
+
+# Ensure that the user has installed the required dependencies
+if ! command -v yt-dlp &> /dev/null
+then
+    echo "yt-dlp could not be found"
+    exit
+fi
+
+# Ensure that the user has installed the required dependencies
+if ! command -v file-rename &> /dev/null
+then
+    echo "file-rename could not be found"
+    exit
+fi
+
+# Download the playlist
 yt-dlp \
   --extract-audio \
   --format "ba[ext=m4a]" \
@@ -8,9 +31,10 @@ yt-dlp \
   --embed-thumbnail \
   --restrict-filenames \
   --output "%(title)s.%(ext)s" \
+  --ppa 'EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop="'"'"'if(gt(ih,iw),iw,ih)'"':'"'if(gt(iw,ih),ih,iw)'"'"'"' \
   "$1"
 
-# This only works for openSUSE
-# TODO: Make it work for other distros
+# Rename the files
+# Currently only supported on openSUSE
 file-rename 'y/A-Z/a-z/' *.m4a
 file-rename 'y/_/-/' *.m4a
